package com.example.firstjetpackcompose

import androidx.lifecycle.ViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow

data class CartData(val name:String,val jop:String,val info:String){}

class MyViewModel : ViewModel(){
    private val _listCartData : MutableStateFlow<List<CartData>> = MutableStateFlow(listOf())
    val list  = _listCartData.asStateFlow()
    fun onCreate(){
        val tempList: MutableList<CartData> = mutableListOf()
        tempList.add(CartData("John Doe", "Software Engineer",
            "John Doe is a skilled software engineer with over 5 years of experience in developing web applications. He specializes in Kotlin and Java. John has worked on numerous projects, including e-commerce platforms and mobile apps. He is proficient in using various frameworks and libraries. In addition to his technical skills, John is known for his problem-solving abilities. He enjoys collaborating with cross-functional teams. John believes in continuous learning and frequently takes online courses to enhance his skills. He is also a mentor for junior developers. In his free time, he loves hiking and exploring nature. John is passionate about open-source contributions and often participates in hackathons. He is dedicated to writing clean and maintainable code. His attention to detail ensures high-quality deliverables. John is an advocate for agile methodologies and enjoys working in dynamic environments. He has a Bachelor's degree in Computer Science. John also has experience with cloud computing and DevOps practices. He values work-life balance and encourages his colleagues to pursue hobbies."))

        tempList.add(CartData("Jane Smith", "Graphic Designer",
            "Jane Smith is a talented graphic designer with a knack for creating stunning visuals. She has a strong background in visual arts and design principles. Jane has worked with various clients, helping them build their brands through effective design. Her portfolio includes logos, brochures, and social media graphics. She is proficient in design software like Adobe Photoshop and Illustrator. Jane enjoys staying updated with the latest design trends. She often participates in design workshops and seminars. Jane believes that creativity is a continuous process. In her personal projects, she experiments with different styles and techniques. She values client feedback and incorporates it into her designs. Jane has a degree in Fine Arts. Her work has been featured in several design exhibitions. She also freelances for various startups. In her spare time, Jane enjoys painting and photography. She is passionate about sustainability and tries to promote eco-friendly design practices. Jane also enjoys mentoring aspiring designers."))

        tempList.add(CartData("Michael Brown", "Data Scientist",
            "Michael Brown is a data scientist with extensive experience in machine learning and data analysis. He has a strong background in statistics and mathematics. Michael has worked on projects that involve predictive modeling and data visualization. He is proficient in programming languages such as Python and R. Michael enjoys solving complex problems using data-driven approaches. He has published research papers on various topics related to data science. Michael is an advocate for ethical AI and data privacy. He frequently speaks at industry conferences and events. In his free time, he enjoys reading about the latest advancements in technology. Michael has a Master's degree in Data Science. He collaborates with teams to develop innovative solutions. He believes in the power of data to drive business decisions. Michael is also a contributor to open-source data science projects. He loves mentoring students and young professionals in the field. Michael enjoys hiking and spending time outdoors."))

        tempList.add(CartData("Emily Davis", "Project Manager",
            "Emily Davis is an experienced project manager with a proven track record in leading successful projects. She excels in communication and team collaboration. Emily has managed projects in various industries, including IT and healthcare. She is proficient in project management tools like Jira and Trello. Emily believes in the importance of stakeholder engagement and satisfaction. She regularly conducts project status meetings to keep everyone informed. Emily holds a PMP certification and continuously seeks to improve her project management skills. She enjoys mentoring junior project managers. In her previous roles, she successfully delivered projects on time and within budget. Emily has a Bachelor's degree in Business Administration. She is passionate about fostering a positive team culture. Emily also participates in community service activities. In her free time, she enjoys cooking and exploring new cuisines."))

        tempList.add(CartData("Robert Wilson", "Marketing Specialist",
            "Robert Wilson is a marketing specialist with a focus on digital marketing strategies. He has a strong background in SEO and content marketing. Robert has worked with numerous brands to enhance their online presence. He enjoys analyzing market trends and consumer behavior. Robert is skilled in using analytics tools to measure campaign effectiveness. He believes in the power of storytelling in marketing. Robert frequently attends marketing conferences to network and learn from industry leaders. He holds a Master's degree in Marketing. In his spare time, he enjoys blogging about marketing insights. Robert is also a mentor for aspiring marketers. He loves experimenting with new marketing tools and techniques. His creativity helps him develop unique marketing campaigns. Robert enjoys working in fast-paced environments. He values teamwork and collaboration. In his free time, he enjoys playing sports and staying active."))

        tempList.add(CartData("Sophia Johnson", "HR Manager",
            "Sophia Johnson is an HR manager with extensive experience in talent acquisition and employee relations. She is passionate about creating a positive work environment. Sophia believes that a happy employee is a productive employee. She has implemented various employee engagement initiatives in her organization. Sophia is skilled in conflict resolution and negotiation. She often conducts training sessions for staff development. She holds a degree in Human Resources Management. Sophia enjoys mentoring young professionals in the HR field. In her free time, she enjoys reading and spending time with her family. She is also an advocate for diversity and inclusion in the workplace. Sophia values continuous improvement and often seeks feedback from employees. She has successfully managed recruitment drives and talent pipelines. Sophia enjoys volunteering for local charities and community programs."))

        tempList.add(CartData("William Martinez", "Web Developer",
            "William Martinez is a web developer with expertise in front-end and back-end technologies. He enjoys building responsive and user-friendly websites. William has experience in using frameworks like React and Angular. He is proficient in HTML, CSS, and JavaScript. William believes in the importance of clean code and documentation. He enjoys collaborating with designers and other developers. William has worked on several high-profile projects in his career. He holds a Bachelor's degree in Computer Science. In his spare time, he enjoys contributing to open-source projects. William is also a tech enthusiast who enjoys learning about new technologies. He loves attending meetups and networking with fellow developers. His problem-solving skills help him tackle challenges efficiently. William values constructive feedback and continuous learning. In his free time, he enjoys gaming and watching tech-related content."))

        tempList.add(CartData("Isabella Garcia", "Content Writer",
            "Isabella Garcia is a talented content writer with a passion for storytelling. She enjoys creating engaging content for various platforms. Isabella has experience in writing blogs, articles, and social media posts. She believes in the importance of understanding the audience. Isabella is skilled in SEO techniques to enhance content visibility. She holds a degree in Communications. In her free time, she enjoys reading fiction and poetry. Isabella frequently attends writing workshops to improve her skills. She is also a mentor for aspiring writers. Isabella loves experimenting with different writing styles. Her creativity shines through in her work. She values constructive feedback and is open to revisions. Isabella enjoys collaborating with marketers and designers. In her spare time, she volunteers at local literacy programs."))

        _listCartData.value = tempList


    }
}